language: php

php:
  - 7.4
  - nightly

matrix:
  allow_failures:
  - php: nightly

before_script: make init

before_install:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
